name: Eksperimen SML Ikrar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Ikrar.py

    - name: Commit and Push Preprocessed Data
      run: |
        git config --global user.name "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git add preprocessing/titanic_preprocessing.csv
        git commit -m "Add preprocessed Titanic data"
        git push --force origin main 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

