name: Eksperimen SML Ikrar

on:
  push:
    paths:
      - 'preprocessing/**'
    branches:
      - main
  pull_request:
    paths:
      - 'preprocessing/**'
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Ikrar.py

    - name: Commit and Push Preprocessed Data
      run: |
        git config --global user.name "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        if [[ -f preprocessing/titanic_preprocessing.csv ]]; then
          git add preprocessing/titanic_preprocessing.csv
          git diff --staged --quiet || git commit -m "Add preprocessed Titanic data"
          git push
        else
          echo "No preprocessed data file found"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

